---

- name: Ensure apt essential packages
  become: yes
  apt:
    name: python-pip

- name: Ensure essential pip packages
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - boto
    - netaddr
