---

driver:
  name: docker

platforms:
  - name: sansible_aws_persistent_volumes-trusty
    image: ubuntu:trusty
  - name: sansible_aws_persistent_volumes-xenial
    image: ubuntu:xenial
  - name: sansible_aws_persistent_volumes-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible
  options:
    tags: build
  lint:
    name: ansible-lint

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 179
        truthy: disable

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
