---

- name: Create network config for ENI
  become: yes
  template:
    dest: "/etc/network/interfaces.d/eth{{ sansible_persistent_network_interfaces_device_index }}.cfg"
    mode: 0644
    src: eth.cfg.j2
  when: persistent_network_interfaces_interface_ip | default(none) is not none
  register: persistent_network_interfaces_config

- name: Bring ENI interface up
  become: yes
  command: "ifup eth{{ sansible_persistent_network_interfaces_device_index }}"
  when: persistent_network_interfaces_config is changed

- name: Update facts with new interface details
  action: setup
  when: persistent_network_interfaces_config is changed
